#
# mdserver/version.py: what it says on the tin.
#

# try and import the mdserver/_version.py file, generated by setuptools_scm
try:
    from . import _version

    VERSION = _version.version
except ImportError:
    VERSION = "0.6.7"

# Note that setuptools_scm doesn't support generating a timestamp for the
# release, so we're left with handling that manually . . .
RELEASE_DATE = "2024-05-11"
